### ISSUE TITLE
[BOUNTY] 70$USD Have Portal Fleshlight and Portal Dildo interactions properly fixed

### ISSUE THREAD

**Issue by KonKonBreezeFox** [SPLURT-Station/S.P.L.U.R.T-Station-13#779]
## Contact:
Novitart#8715
(Bounty opened by ≠KonKon, the Fairydragon≠#8089)

## About the Bounty
Using the Portal Fleshlight [and Portal Dildo] doesnt properly cum into the portal pantie wearer [and into the portal dildo user] and instead lands on the floor. The fix for this would entail having both fixed and the pregnancy mechanics for it working properly.

**Comment by The-Sun-In-Splendour** [comment]
Bro really put a 70 USD bounty for a 6 line change

**Comment by Neliahawk** [comment]
if "6 lines are too easy" what about this idea:
(atleast i think it would be good to have the option to turn these options on/off when desired)

Using the panties opens a menu similar to "radio or remote signaler".
in there you can turn on/off:
-Allow fluid transfer (semen)
-Allow Egg transfer (for inert eggs)
-Panties anonymity (panty wearer wearer will show as "unknown" in interaction messages when turned on)
-Portal anonymity (portal wearer will show as "unknown" in interaction messages when turned on)
-Multilink (able to link these panties to multiple portals)
-a "Portal finder" button. (when clicked it shows the range and direction of your linked portals under it like: portal-range 83-SW, portal-range 163-N) (then again you wont be able to use the finder, if you wear the panties as you cant use them in hand... maybe as a rightclick menu option that opens a window with that? hmm)

**Comment by Azarak** [comment]
Fluid transfer and anonymity are working properly, and it ended up being 131 lines after all

I haven't interacted with any egg content so I am not even sure what you're referring to, or how difficult that would be to implement

A portal finder would sort of defeat the purpose of the anonymity, I think it would ruin a part of the fun, but I'm not the one who made the bounty.

**Comment by Azarak** [comment]
Alright I see what was the problem for some issues. It would fail to identify a vagina organ if the vagina was not exposed (through IC verb), and then it would fail to do egg magic and pregnancy magic. It was fixed on the PR and should work on the next deployment

![image](https://user-images.githubusercontent.com/6381979/229307409-1e5994c7-1dbc-4419-9a8a-3cdd9d186458.png)

**Comment by Neliahawk** [comment]
> Fluid transfer and anonymity are working properly, and it ended up being 131 lines after all
> 
> I haven't interacted with any egg content so I am not even sure what you're referring to, or how difficult that would be to implement
> 
> A portal finder would sort of defeat the purpose of the anonymity, I think it would ruin a part of the fun, but I'm not the one who made the bounty.

yea with egg stuff i meant the options to "lay inert eggs" (oviposition stuff) in people through portals.

with portal finder i meant something like the "custodial locator" the janitor has on their pda cartridge:
-a "portal finder pda cartridge" new item in the portal box.
and when inserted into your pda it checks if you wear any portal panties on your body (mouth/groin).
and then for these panties it scans for "linked portals" to these and shows where they are located. same as the janitor locator locates mops/buckets/janicarts.
(it probably can even use similar code from how it works with the janitor items and "custodipro cardtridge".
it "just" needs to have code to just show the portal locations of portals linked to the panties the pda user wears.)
so that way you yourself can always locate the portals that are in use, incase people dump them in a locker or they get "misplaced", so you cyn refind them. (its not for "random people to find these items. that is why a pda cartridge might actually works well for this if it can be made to "scan for panties you wear" and then "list the portals linked to what you wear".)
(but i guess this isnt exactly part of the bounty XD but i thought i mention this anyways. maybe i should add this in the discord suggestions instead hmm)

oh also maybe check if condoms properly prevent fluid transfer.
and if turning off "egg stuffing" prevents eggs from going through portals.
and maybe check if fluids actually get added to the other person through portal sex? (i.e are scanable with the med scanner that they are inside, well however that works with normal sex.)

and up there the line "You laid an egg inside Shanika Jardine's the vagina."   <- that line probably should also be anonymous like "you laid an egg inside the portals vagina."  (i think the "the vagina" is generally "wrong" to have the "the" there? but i guess that is a text thing for the egg interactions and not related to portals.)

if ya need a "2nd text person" to test all this and check if everything works properly i could join sometime to help out now that someone is actually working on this stuff.

**Comment by Azarak** [comment]
Oh you are right, I need to make the anonymity be retained on the oviposition stuff
Regarding the grammar errors - I did not write or modify those
